Added Mourer Rose Pattern
yashlamba/simulate pull request #102
Opened 2020-03-05 07:52 UTC by kmrakash

2020-03-05 07:53 UTC, kmrakash commented
It's Working FIne

2020-03-05 10:17 UTC, shreyamalviya commented on lib/src/data/simulations.dart
> +    7: "moure rose pattern"
@kmrakash, just scanned this for now and I noticed that the spelling is wrong at a _lot_ of places in the PR, so you should probably fix that and keep it in mind for next time. It's "Maurer". 

Great effort, by the way!

2020-03-05 10:23 UTC, shreyamalviya requested changes
Remove ".svg" from the filename

2020-03-05 11:04 UTC, kmrakash commented
.svg is mandatory for this file otherwise figure disappear . I tried it

2020-03-12 12:54 UTC, shreyamalviya requested changes
Again, the spelling is "Maurer". Please fix it at _all_ the places where it is wrong.
Other than that, LGTM.

@yashlamba, can you make the final image for this one?

2020-03-12 12:54 UTC, shreyamalviya commented on lib/src/simulations/mourer_rose.dart
> +                 // style: Theme.epicycloid_curveof(context).textTheme.subtitle,
stray comment

2020-03-12 12:54 UTC, shreyamalviya commented on lib/src/data/simulations.dart
> +    7: "mourer rose pattern"
spelling

2020-03-12 15:32 UTC, yashlamba commented
@sakshamarora1 and @yashugarg can help review this further!?

2020-03-13 13:10 UTC, kmrakash commented
Oh sorry it should be "Maurer", my mistake ,
Anything else i have to made changes please let me know . 
Before this my only motive was to function properly . I have not care that much on spellings . Let me correct these
Thanx for review

2020-03-16 11:35 UTC, sakshamarora1 requested changes
It looks really good!
Just a little tweaks and I think it's good to go!

2020-03-16 11:41 UTC, sakshamarora1 requested changes
It looks really good!
Just a little tweaks and I think it's good to go!

2020-03-16 11:41 UTC, sakshamarora1 commented on lib/src/simulations/maurer_rose.dart
> +  MaurerRosePainter(
How about passing a color parameter and then keeping the color of inner lines opposite to the theme of the app.

2020-03-16 11:43 UTC, sakshamarora1 commented on lib/src/simulations/maurer_rose.dart
> +      painter: MaurerRosePainter(
Just pass ``Theme.of(context).accentColor`` and assign color to paint.color in the CustomPainter

2020-03-16 11:45 UTC, sakshamarora1 commented on lib/src/simulations/maurer_rose.dart
> +        this.points.add(Offset(x/2,y/2)
The curve is not filling up the screen completely so how about changing this to be divided by 1.5
same goes for all other instances of this

2020-03-16 11:46 UTC, sakshamarora1 commented on lib/src/simulations/maurer_rose.dart
> +    ..strokeWidth = thickness;
There's no need to keep the thickness of the inner lines the same as the outer curve. let's just keep it constant to 1?

2020-04-03 13:02 UTC, kmrakash commented
@sakshamarora1  now it is showing some conflicts , How can i resolve ?? Please Help

2020-04-04 12:08 UTC, sakshamarora1 commented
@kmrakash No worries, I've resolved it. Thank you!
There was a conflict because another PR got merged recently.

2020-04-04 12:12 UTC, kmrakash commented
Thank you @sakshamarora1 , will it merge now ??

2020-04-07 06:28 UTC, yashlamba approved these changes
This looks good to merge, just make sure to remove the svg file before merging @sakshamarora1. Good work @kmrakash.

2020-04-07 10:48 UTC, merged