fix: added rose pattern animation (#71)
yashlamba/simulate pull request #121
Opened 2020-04-29 08:56 UTC by 991rajat

Fixed #71

2020-05-01 18:52 UTC, sakshamarora1 requested changes
Nice work!
Just a few things - 
- When both the numerator and denominator are 0, an error is thrown & both `k ~` and `animate` checkbox get dislocated. Can you take a look at that? and let me know if there are any doubts.
- I think we need to refactor the code a bit so that the pattern doesn't go out of screen when `Offset` value is increased.
- Also, we can make the animation a bit faster. :)

2020-05-03 18:53 UTC, 991rajat commented
@sakshamarora1 
I need help with the second point.

> (I think we need to refactor the code a bit so that the pattern doesn't go out of screen when Offset value is increased.)

2020-05-13 11:52 UTC, sakshamarora1 reviewed
Don't worry about the offset issue as it looks fine as it is for now. We can take care of that later if need be.
Just a few minor changes left.

2020-05-13 11:52 UTC, sakshamarora1 commented on lib/src/simulations/rose_pattern.dart
>        bottomNavigationBar: Container(
This is an older simulation so we haven't implemented a `ListView` widget like in Lissajous Curve. Just change the Column child to ListView similarly to how it's been done in [Lissajous Curve](https://github.com/cod-ed/simulate/blob/master/lib/src/simulations/lissajous_curve.dart).

2020-05-13 11:52 UTC, sakshamarora1 commented on lib/src/simulations/rose_pattern.dart
> +  void clearScreen() {
When the screen is cleared,the simulation starts from the beginning. Instead we can have it start right where it left off. That would become the starting point for the animation!
For reference you can check out [Lissajous Curve](https://github.com/cod-ed/simulate/blob/master/lib/src/simulations/lissajous_curve.dart).

2020-05-13 11:52 UTC, sakshamarora1 commented on lib/src/simulations/rose_pattern.dart
> +        sleep(Duration(milliseconds: 1));
Can you make the animation a bit faster while keeping it smooth? I tried changing these values but couldn't find a good match.

2020-05-13 15:43 UTC, sakshamarora1 reviewed
I noticed the first animation was not completing the pattern. Also change the height of bottom navigation bar to be a fifth of the screen instead of fourth of the screen.

Important: As I mentioned before, you haven't considered the case where denominator is equated to 0 while it's animating. Its throwing an exception.

2020-05-13 15:43 UTC, sakshamarora1 commented on lib/src/simulations/rose_pattern.dart
>    nextStep()
`looplength = 2 * pi * widget.d;` in the if statement is not needed as we are updating looplength in `clearScreen()`.

2020-05-13 15:43 UTC, sakshamarora1 commented on lib/src/simulations/rose_pattern.dart
> +        loopi += 0.05;
```suggestion
        loopi += 0.04;
```

2020-05-13 15:43 UTC, sakshamarora1 commented on lib/src/simulations/rose_pattern.dart
>        if(!(widget.d==0)&&!(widget.d==0&&widget.n==0)){
```suggestion
      if(loopi == 0) {
        looplength = 2 * pi * widget.d;
      }
      if(!(widget.d==0)&&!(widget.d==0&&widget.n==0)){
```

`looplength` depends on `widget.d` that's why the first animation is always short, because initially it's value is 2pi and is not multiplied by `widget.d`.

2020-05-14 18:26 UTC, 991rajat commented
@sakshamarora1 "As I mentioned before, you haven't considered the case where denominator is equated to 0 while it's animating. Its throwing an exception."
I don't find while running it.

2020-05-15 03:55 UTC, sakshamarora1 commented
@991rajat That's weird. I was getting that error till yesterday!

2020-05-31 10:20 UTC, merged