Added support for landscape view
yashlamba/simulate pull request #133
Opened 2020-10-19 11:55 UTC by sakshamarora1

Added support for landscape view in the following simulations:

  - Epicycloid (Pencil of Lines)
  - Epicycloid Curve
  - Lissajous Curve
  - Maurer Rose
  - Rose Pattern

2020-10-23 10:35 UTC, yashlamba commented
These are the major problems I have noticed (Flutter for Web):
1. Rose Pattern returns the following error when in landscape and denominator = 0
`Another exception was thrown: RangeError (index): Index out of range: no indices are valid: 0`
![image](https://user-images.githubusercontent.com/44164398/96993043-5f8f7d80-1548-11eb-9890-3a2cd71f33b0.png)
> The spacing between the sliders also needs to be adjusted for all simulations, as evident above.

2. Toothpick Pattern has an overflow error in landscape mode, might get fixed by some minor adjustments.

3. Lissajous Throws the same error as Rose Pattern once animate is true. It might have issues with sleep function but the UI also disfigures.

4. Animate is not working with many simulations, maybe we can get rid of the sleep issue in this PR only.

2020-10-23 10:36 UTC, yashlamba commented on lib/src/simulations/epicycloid.dart
> -  }
We can't just get rid of these methods, just remove the orientation stuff.

2020-10-23 10:37 UTC, yashlamba reviewed
I'll review further ASAP.

2020-10-25 18:57 UTC, yashugarg requested changes
- [ ] Remove SizedBox() from List view when in landscape mode from all simulations.
- [ ] In Epicycloid Pattern (Pencil of Lines), "Points" overlaps the curve.
![Screenshot_2020-10-26-00-24-01-88_6722ee9149bcc9e95a5626b4285cc503 1](https://user-images.githubusercontent.com/53790154/97116233-e186ce80-1721-11eb-85a1-0b5268985c1d.jpg)

2020-10-26 14:00 UTC, yashlamba requested changes
Getting rid of the sized boxes is necessary, they don't add to the UI. I like how everything works now though, I didn't have any other immediate issues on Pixel 2 XL. Great work!

2020-10-26 14:00 UTC, yashlamba commented on lib/src/simulations/toothpick.dart
> -    ]);
I think we should keep this for toothpick pattern?

2020-10-26 20:02 UTC, sakshamarora1 commented on lib/src/simulations/toothpick.dart
> -    ]);
Yeah, my bad, I'll remove that.

2020-10-27 11:18 UTC, yashlamba commented
Fix for the range error/distorted UI: 
https://github.com/cod-ed/simulate/blob/9524b04a5617bda2a1423b642424ed325fc08484/lib/src/simulations/rose_pattern.dart#L367
to
```dart
if (points.length > 0) {
      canvas.drawPoints(PointMode.polygon, points, paint);
}
```

2020-10-27 20:39 UTC, yashlamba approved these changes

2020-10-28 06:51 UTC, yashugarg approved these changes

2020-10-28 07:44 UTC, merged