lib:simulations:selection_sort:Selection sort implemented
yashlamba/simulate pull request #170
Opened 2021-03-25 14:58 UTC by apoorvdwi

Fixed #162

2021-03-27 13:56 UTC, yashugarg requested changes
@apoorvdwi the sorting algorithm works fine but it'd be great if you could show every iteration of the loop when searching for the next smallest element to swap.

2021-05-19 07:05 UTC, yashugarg approved these changes
Great work
just remove "(Bars)" form the name

2021-05-24 15:18 UTC, sakshamarora1 reviewed
Looks good! Just a few minor changes and it will be ready to be merged!

2021-05-24 15:18 UTC, sakshamarora1 commented on lib/src/data/simulations.dart
> +    9: "maurer rose pattern mathematics animation"
Don't add the new simulation in between. Add it at the end.

2021-05-24 15:18 UTC, sakshamarora1 commented on lib/src/data/simulations.dart
> +        simulationName: 'Selection Sort',
Here too. Move it to the end and restore the original ids of the existing simulations.

2021-05-24 15:18 UTC, sakshamarora1 commented on lib/src/data/simulations.dart
> +            : 'assets/simulations/SelectionSortLight.png',
I believe we can re-use the `InsertionSort` image assets and we can remove the new ones.

2021-05-24 15:48 UTC, apoorvdwi commented
Applied the changes suggested by @sakshamarora1

2021-05-24 18:36 UTC, sakshamarora1 approved these changes

2021-05-24 18:38 UTC, merged