lib:simulations:hypocycloidcurve:Hypocycloid Curve implemented
yashlamba/simulate pull request #180
Opened 2021-03-30 22:28 UTC by Snehaa1203

fixed #164

2021-05-19 07:37 UTC, yashugarg requested changes
the simulation works fine
great work
just do these small changes

2021-05-19 07:37 UTC, yashugarg commented on lib/src/data/simulations.dart
>    static var _favorites = [-1, -1, -1, -1, -1, -1, -1, -1, -1];
add another "-1" to _favorites array
and a "9" to the _mathematics arra

2021-05-19 07:37 UTC, yashugarg commented on lib/src/data/simulations.dart
> +            ? 'assets/simulations/Epicycloid1Dark.png'
put the right images associated with your simulation

2021-05-19 07:37 UTC, yashugarg commented on lib/src/simulations/Hypocycloid.dart
> +      smallCenter = Offset((innerRadius + outerRadius) * cos(time),
make it 
innerRadius - outerRadius
to display the rotating circle inside the base circle

2021-05-20 17:55 UTC, Snehaa1203 reviewed
I have made the changes.
Please accept the PR

2021-05-31 12:52 UTC, yashugarg approved these changes

2021-05-31 13:09 UTC, merged