CI: Add checks for linting, building APK and building web
yashlamba/simulate pull request #197
Opened 2022-01-13 07:11 UTC by Saransh-cpp

## Changes/Additions
- Added lint instructions in `analysis_options.yaml`
- Formatted all the files (to pass the lint check)
- Added a new workflow to check lint, build apk, and build web

2022-01-13 07:17 UTC, Saransh-cpp commented
I think I still had that old commit somewhere in my git history (probably committed to master at that time). Also, weirdly the workflows are not running, I'll look into it.

2022-01-15 09:05 UTC, yashlamba requested changes
@Saransh-cpp can you remove all the other changes from this PR and just keep the CI, if you feel other things are relevant, you can open another PR. This will make reviewing a lot easier.

2022-01-15 09:54 UTC, Saransh-cpp commented
On it!

2022-01-15 10:01 UTC, Saransh-cpp commented
I will create another PR to lint all the files, fixing the lint check.

2022-01-20 09:14 UTC, yashlamba commented on .github/workflows/checks.yml
> +name: Checks
```suggestion
name: build-checks
```

2022-01-20 09:15 UTC, yashlamba commented on .github/workflows/checks.yml
> +
```suggestion
```

2022-01-20 09:24 UTC, yashlamba requested changes

2022-01-20 09:24 UTC, yashlamba commented on .github/workflows/checks.yml
> +  build-apk-and-web:
Let's separate out the builds for web and android.

2023-09-10 06:04 UTC, Saransh-cpp commented
Closing this PR.

I am cleaning up my open PRs and closing the stale ones. Please let me know if the changes are required in the future. I would be more than happy to re-open and work on this.

2023-09-10 06:04 UTC, closed without merging