lib: src: simulations: Added Pi Approximation Simulation #54
yashlamba/simulate pull request #55
Opened 2019-07-21 07:41 UTC by akshansh2000

Added Pi Approximation using Monte Carlo method
Closes #54

2019-07-21 07:55 UTC, yashlamba requested changes
Rest looks good, but it never stabilizes over 2 digits even when I ran it for more that 3-4 mins, is it okay?

2019-07-21 07:55 UTC, yashlamba commented on lib/src/data/simulations.dart
> +        simulationName: 'Pi Approximation',
Simulation name is very generic, would be better if you could change it to something specific

2019-07-25 11:36 UTC, yashlamba approved these changes

2019-07-25 11:41 UTC, yashlamba commented
Planning to make any more changes?

2019-07-25 12:07 UTC, akshansh2000 commented
> Planning to make any more changes?

Nope. Anything else required?

2019-07-25 13:00 UTC, yashlamba commented
> > Planning to make any more changes?
> 
> Nope. Anything else required?

nope

2019-07-25 13:00 UTC, merged