lib: src: simulations: Added Epicycloid Pedal curve simulation
yashlamba/simulate pull request #78
Opened 2020-02-03 07:45 UTC by yashugarg

closes #77

2020-02-03 15:27 UTC, sakshamarora1 reviewed
- [x] Fixing the Scaffold rebuilding issue
- [x] Add a checkbox "Animate: "to give an option to view the animation
- [x] Add pause/play and restart buttons (to be visible only when the animate parameter is true" (use Visibility() )
- [x] Make the value of k have upto 2 decimal places

- [Here](https://en.wikipedia.org/wiki/Epicycloid#/media/File:EpitrochoidOn3-generation.gif) the line size is not varying, but in the animation it is varying. Let's keep it constant at radius size for now and discuss it later.
- At high amplitude and low k value the curve is not completely in the screen width.
- At high frequency the curve isn't smooth.

Fix these issues and then let's discuss the line size variation.
You can refer to the [Lissajous Simulation](https://github.com/cod-ed/simulate/blob/master/lib/src/simulations/lissajous_curve.dart) for reference.

2020-02-03 15:27 UTC, sakshamarora1 commented on lib/src/simulations/epicycloid_pedal.dart
> +    WidgetsBinding.instance.addPostFrameCallback((_) => update());
The Scaffold is being rebuilt at every frame which slows down the animation and is not a good approach when animating. Instead extract the CustomPaint as a new StatefulWidget and make changes in that widget so that only the screen area given to the CustomPainter is rebuilt.

2020-02-03 15:27 UTC, sakshamarora1 commented on lib/src/simulations/epicycloid_pedal.dart
> +                child: CustomPaint(
Extract CustomPaint here as Widget and convert it to a StatefulWidget

2020-02-15 17:36 UTC, sakshamarora1 reviewed
Excellent Work!! Sorry for the delay.
Here are a few things that are left :
1. Can you keep the color of the of the pause and clear buttons white.
2. The color of inner circle be white and the outer circle be blue. also keep the inner circle hollow when it's not animating...
3. Adding a sizedBox in bottomNavigationBar above the _k slider.
4. When the curve is cleared , can you keep the outer circle at the current position instead of it going back to the starting position.
Thanks. Great Work! :)

2020-02-16 10:17 UTC, sakshamarora1 commented
Oops! I think you forgot to change the color of the main circle to white when animate is off.
Also you should keep the width and height to your own device's width and height on line 49 and 50.
Just these 2 small changes and then @yashlamba will finally review it before merging it. :)
Great Work!!

2020-02-16 14:45 UTC, yashlamba commented on lib/src/simulations/epicycloid_pedal.dart
> +                heroTag: 1,
We can probably change this to null.

2020-02-16 14:47 UTC, yashlamba requested changes

2020-02-16 14:47 UTC, yashlamba commented on lib/src/simulations/epicycloid_pedal.dart
> +      height: MediaQuery.of(context).size.height,
This has to be constant values of the designers mobile device, you can print them in the terminal and change them to that.

2020-02-16 14:48 UTC, yashlamba commented
I'll probably refactor some of the code related to cards and simulation UI. I will rebase this branch with that and merge it! Most of your part is done. Great work!

2020-02-20 08:02 UTC, yashlamba commented
Can you please change the ID as #76 was merged recently? This is almost ready to go!

2020-02-24 14:49 UTC, sakshamarora1 requested changes
Apart from these pending changes, the PR is ready to go!

2020-02-24 14:49 UTC, sakshamarora1 commented on ios/Flutter/flutter_export_environment.sh
> +export "FLUTTER_FRAMEWORK_DIR=C:\src\flutter\bin\cache\artifacts\engine\ios"
This has to be left unchanged as before i.e. according to Yash's machine.

2020-02-24 14:49 UTC, sakshamarora1 commented on lib/src/simulations/epicycloid_pedal.dart
> +      height: MediaQuery.of(context).size.height,
This change is still pending.

2020-02-24 14:49 UTC, sakshamarora1 commented on lib/src/simulations/epicycloid_pedal.dart
> +                heroTag: 1,
This change is still pending too.

2020-02-26 07:05 UTC, yashlamba commented
Awesome work, I will push a few tweaks and merge it! Thank you for contributing.

2020-03-16 15:56 UTC, sakshamarora1 reviewed
Can you make it so that when the curve animation is completed it restarts.

2020-03-16 15:56 UTC, sakshamarora1 commented on lib/src/simulations/epicycloid.dart
> +                    outerRadius = value.toInt();
On changing the value of `R` , value of 'r' assumes the same value as `R`.

2020-04-01 05:53 UTC, yashlamba commented on lib/src/simulations/epicycloid.dart
> +                  heroTag: Null,
```suggestion
                  heroTag: null,
```

2020-04-01 05:54 UTC, yashlamba commented on lib/src/simulations/epicycloid.dart
> +                heroTag: Null,
```suggestion
                heroTag: null,
```

2020-04-01 05:55 UTC, yashlamba commented on lib/src/simulations/epicycloid.dart
> +                ),
We can get rid of scale now, I don't think it is required.

2020-04-01 06:00 UTC, yashlamba requested changes
These are some minor changes needed, it's ready to merge. Thank you, really amazing work!

2020-04-01 06:02 UTC, yashlamba commented on lib/src/simulations/epicycloid.dart
> +                  ),
The fill needs to be red when selected, and the button needs to be disabled when animating. Check epicycloid_curve for reference.

2020-04-01 06:03 UTC, yashlamba requested changes

2020-04-01 06:03 UTC, yashlamba commented on lib/src/simulations/epicycloid.dart
> +                  ),
The fill needs to be red when selected, and the button needs to be disabled when animating. Check epicycloid_curve for reference.

2020-04-02 18:37 UTC, merged