Update pubspec.yaml
yashlamba/simulate pull request #86
Opened 2020-02-29 18:56 UTC by himanshusharma89

Updated pubspec.yaml with latest versions of packages, for issue #85 .

2020-03-01 04:52 UTC, yashlamba requested changes

2020-03-01 04:52 UTC, yashlamba commented on pubspec.yaml
>    cupertino_icons: ^0.1.2
can you update this and squash the commits into one.

2020-03-01 04:53 UTC, yashlamba commented
Great work! I am labeling this with the score and will merge this when provider migration is done #84.

2020-03-02 17:35 UTC, himanshusharma89 commented
Hey @yashlamba, I have resolved the issue #84 
So you can merge both PR: #86 and #92

2020-03-03 18:45 UTC, yashlamba approved these changes

2020-03-11 07:22 UTC, merged